backend:
  name: git-gateway
  branch: main

local_backend: true

publish_mode: editorial_workflow
media_folder: public/content/assets
public_folder: content/assets

collections:
  - label: "Data"
    name: "data"
    files: 
      - label: "Metadata"
        name: "metadata"
        file: "public/content/meta.json"
        format: json
        fields:
          - { label: Title, name: title, widget: string}
          - { label: Portrait, name: portrait, widget: image, required: false }
          - { label: About, name: about, widget: markdown, required: false,  minimal: true, buttons: [bold, italic, link]}
          - { label: Contact, name: contact, widget: string }  
          - label: "Socials"
            name: "socials"
            widget: list
            required: false
            fields:
              - label: "Platform"
                name: "platform"
                widget: select
                options:
                  - { label: Facebook, value: "facebook" }
                  - { label: Instagram, value: "instagram" }
                  - { label: Twitter, value: "twitter" }
                  - { label: TikTok, value: "tiktok" }
                  - { label: Bandcamp, value: "bandcamp" }
                  - { label: Spotify, value: "spotify" }
                  - { label: SoundCloud, value: "soundcloud" }
                  - { label: Apple Music, value: "apple" }
              - { label: Text, name: text, widget: string }  
              - { label: URL, name: url, widget: string }  
              - { label: Show, name: show, widget: boolean }
          - label: "SEO"
            name: "seo"
            required: false
            fields:
              - { label: Description, name: description, widget: string }
              - { label: URL, name: url, widget: string }   
              - label: "Tags"
                name: "tags"
                widget: text
      - label: "Schedule"
        name: "schedule"
        file: "public/content/schedule.json"
        format: json
        fields:
          - label: "Dates"
            name: "dates"
            widget: list
            required: false
            fields:
              - { label: Start, name: start, widget: datetime }
              - { label: End, name: end, widget: datetime, required: false  }
              - { label: Description, name: description, widget: markdown, required: false,  minimal: true, buttons: [bold, italic, link] }
              - { label: Venue, name: venue, widget: string }
              - { label: Location, name: location, widget: string }
              - { label: Link, name: link, widget: string, required: false }
      - label: "CV"
        name: "cv"
        file: "public/content/cv.json"
        format: json
        fields:
          - label: "Entries"
            name: "entries"
            widget: list
            required: false
            fields:
              - label: "Type"
                name: "type"
                widget: select
                options:
                  - { label: Education, value: "Education" }
                  - { label: Exhibitions, value: "Exhibitions" }
                  - { label: Writing, value: "Writing" }
                  - { label: Credits, value: "Credits" }
              - { label: Start, name: start, widget: date }
              - { label: End, name: end, widget: date, required: false }
              - { label: Title, name: title, widget: string }
              - { label: Subtitle, name: subtitle, widget: string, required: false }
              - { label: Location, name: location, widget: string, required: false }
              - { label: Body, name: body, widget: widget: markdown, required: false,  minimal: true, buttons: [bold, italic, link] }
              - { label: Link, name: link, widget: string, required: false  }
      - label: "Gallery" 
        name: "gallery"
        file: "public/content/gallery.json"
        format: json
        fields: 
          - label: "Images"
            name: "images"
            widget: list
            required: false
            fields:
              - { label: Image, name: image, widget: image }
              - { label: Caption, name: caption, widget: markdown, required: false,  minimal: true, buttons: [bold, italic, link]}
